- hosts: all
  become: true
# tasks that should be run first or before all other tasks
  pre_tasks:
  - name: install updates
    tags: always
    package:
      upgrade: yes
      update_cache: yes
# adding terraform to the workstation(db)
# only for practice purposes do not do this irl
- hosts: workstations
  become: true
  tags: workstation
  tasks:
  - name: install unzip
    package:
      name: unzip
  - name:
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.0.10/terraform_1.0.10_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: alex
      group: alex

# installs apache and php packages regardless of OS 
- hosts: webservers
  become: true
  tasks:
  - name: install apache and php packages
    tags: apache,apache2,php
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
# copies machine file and distributes to webserver
  - name: copy default html file for site
    tags: html
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: alex
      group: alex
      mode: 0644
# installs database 
- hosts: db_servers
  become: true
  tasks:
  - name: install mariadb package
    tags: db,mariadb,maria
    package:
      name: "{{ maria_db_package }}"
      state: latest
